web/web/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#from isobres.views import *
from gestorFestes.views import *
#FORMS
from gestorFestes.forms import CiutatForm
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = patterns('',
    # Examples:
    url(r'^$', index, name='Inici'),
    # url(r'^web/', include('web.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^/$', index),
	url(r'^admin/', include(admin.site.urls)),
	

	# Llistar festes
	url(r'^festes/$', festes, name='festa_lis'),

	# Crear Festa
	url(r'^festes/create/$', FestaCreate.as_view(),name='festa_create'),

	# Mostrar detall festa
	url(r'^festes/(?P<idFesta>\w+)/$', festa_info, name='festa_detail'),

	# Modificar Festa
	url(r'^festes/(?P<pk>\d+)/edit/$', FestaUpdate.as_view(),name='festa_edit'),

    # Borrar Festa
	url(r'^festes/(?P<pk>\d+)/delete/$', FestaDelete.as_view(),name='festa_delete'),

	# Mostrar detall festa de local concret	
	url(r'^festesLocal/festa/(?P<idFesta>\w+)/$',festa_info),

	# Mostrar llista festes de local concret
	url(r'^festesLocal/(?P<idLocal>\w+)/$',festes_local),

    
	# Crear ciutat
    url(r'^ciutats/create$', CiutatCreate.as_view(),name='ciutat_create'),

	# Modificar ciutat
	url(r'^ciutats/(?P<pk>\d+)/edit/$', CiutatUpdate.as_view(),name='ciutat_edit'),

	# Borrar ciutat
	url(r'^ciutats/(?P<pk>\d+)/delete/$', CiutatDelete.as_view(),name='ciutat_delete'),

	# Llista de ciutats
    url(r'^ciutats/$', ciutats, name='ciutat_lis'),

	# Detall de ciutat
	url(r'^ciutats/(?P<idCiutat>\w+)/$', ciutat_info,name='ciutat_detail'),


	# Crear Local
    url(r'^locals/create/$', LocalCreate.as_view(),name='local_create'),

	# Modificar Local
	url(r'^locals/(?P<pk>\d+)/edit/$', LocalUpdate.as_view(),name='local_edit'),

	# Borrar Local
	url(r'^locals/(?P<pk>\d+)/delete/$', LocalDelete.as_view(),name='local_delete'),

	# Detall Local
    url(r'^locals/(?P<idLocal>\w+)/$',locals_info, name='local_detail'),

	# Llsita Locals	
	url(r'^locals/$',locals_view, name='local_lis'),

	# Crear review
	url(r'^locals/(?P<pk>\d+)/reviews/create/$', review, name='review_create'),


    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
                    { 'next_page' : '/'}),
	#url(r'^login/control$', controlLogin),
	url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),

)

#RESTful API
urlpatterns += patterns('',

	# llistar Locals
	url(r'^api/locals/$', APILocalList.as_view(), name='local-list'),

	# Detall Local
	url(r'^api/locals/(?P<pk>\d+)/$', APILocalDetail.as_view(), name='local-detail'),


	# Llistar ciutats
	url(r'^api/ciutats/$', APICiutatList.as_view(), name='ciutat-list'),

	# Detall ciutat
	url(r'^api/ciutats/(?P<pk>\d+)/$', APICiutatDetail.as_view(), name='ciutat-detail'),


	# Llistar festes
	url(r'^api/festes/$', APIFestaList.as_view(), name='festa-list'),

	# Detall festa
	url(r'^api/festes/(?P<pk>\d+)/$', APIFestaDetail.as_view(), name='festa-detail'),
)

if settings.DEBUG and settings.STATIC_ROOT:
    urlpatterns += patterns('',
        (r'%s(?P<path>.*)$' % settings.STATIC_URL.lstrip('/'), 
            'django.views.static.serve',
            {'document_root' : settings.STATIC_ROOT }),)

web/gestorFestes/models.py
#encoding:utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth import models as auth_models
from django.contrib.auth.management import create_superuser
from django.db.models import signals
from django.conf import settings
from datetime import date

# Prevent interactive question about wanting a superuser created.  (This code
# has to go in this otherwise empty "models" module so that it gets processed by
# the "syncdb" command during database creation.)
signals.post_syncdb.disconnect(
    create_superuser,
    sender=auth_models,
    dispatch_uid='django.contrib.auth.management.create_superuser')


# Create our own test user automatically.

def create_testuser(app, created_models, verbosity, **kwargs):
  if not settings.DEBUG:
    return
  try:
    auth_models.User.objects.get(username='admin')
  except auth_models.User.DoesNotExist:
    print '*' * 80
    print 'Creating Admin user -- login: admin, password: admin'
    print '*' * 80
    assert auth_models.User.objects.create_superuser('admin', 'x@x.com', 'admin')
  else:
    print 'Test user already exists.'

signals.post_syncdb.connect(create_testuser,
    sender=auth_models, dispatch_uid='common.models.create_testuser')

# Create your models here.

class Ciutat(models.Model):
	provincia = models.CharField(max_length=25)
	nom = models.CharField(max_length=25, unique=True, verbose_name="Ciutat")
	cp = models.IntegerField(verbose_name='Codi Postal')
	user = models.ForeignKey(User, blank=False)
	def __unicode__(self):
		return self.nom
	def get_absolute_url(self):
		return reverse('ciutat_detail', kwargs={'idCiutat': self.id})

class Local(models.Model):
	nom = models.CharField(max_length=25, unique=True)
	descripcio = models.TextField(max_length=200)
	carrer = models.TextField(max_length=50)
	telf = models.IntegerField(verbose_name='Telefon')
	email = models.EmailField(verbose_name='Email de contacte', max_length="30")
	ciutat = models.ForeignKey(Ciutat)
	user = models.ForeignKey(User, blank=False)
	def __unicode__(self):
		return self.nom
	def get_absolute_url(self):
		return reverse('local_detail', kwargs={'idLocal': self.id})


class Festa(models.Model):
	titol = models.CharField(max_length=25, unique=True)
	descripcio = models.TextField(max_length=200)
	imatge = models.ImageField(upload_to='imatgesFesta', verbose_name='Imatge', null = True, blank= True)
	data = models.DateField()
	local = models.ForeignKey(Local)
	user = models.ForeignKey(User, blank=False)
	def __unicode__(self):
		return self.titol
	def get_absolute_url(self):
		return reverse('festa_detail', kwargs={'idFesta': self.id})

class Review(models.Model):
	RATING_CHOICES = ((1,'1'),(2,'2'),(3,'3'),(4,'4'),(5,'5'))
	rating = models.PositiveSmallIntegerField('Ratings (stars)', blank=False, default=3, choices=RATING_CHOICES)
	comment = models.TextField(blank=True, null=True)
	user = models.ForeignKey(User, blank=False)
	date = models.DateField(default=date.today)

	#class Meta:
	#	abstract = True

class LocalReview(Review):
	local = models.ForeignKey(Local)

web/gestorFestes/forms.py
from django.forms import ModelForm
from django import forms
from gestorFestes.models import Ciutat, Local, Festa
from django.contrib.auth.models import User

class CiutatForm(ModelForm):

	class Meta:
		model = Ciutat
		exclude = ['user']

class LocalForm(ModelForm):
	
	class Meta:
		model = Local
		exclude = ['user']

class FestaForm(ModelForm):

#	def __init__(self, *args, **kwargs):
#		locals_user = kwargs.pop('locals_user', None)
#		super(FestaForm, self).__init__(*args, **kwargs)
#		self.fields['local'] = forms.ModelChoiceField(locals_user)
		

	class Meta:
		model = Festa
		exclude = ['user']

web/gestorFestes/views.py
# Create your views here.
from django.http import HttpResponse, Http404
from django.template import Context
from django.template.loader import get_template
from django.contrib.auth.models import User
from gestorFestes.models import Festa,Ciutat,Local,LocalReview
from django.shortcuts import render, render_to_response
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core import urlresolvers

def festes(request): 
	try:
		festes = Festa.objects.all()
	except:
		raise Http404('Festes not found')
	variables = Context({
		'festes': festes,	
        'titlehead': 'Gestor de Festes',
		'pagetitle': 'Festes',
	})

	return render(request,"festes.html",variables)

def festa_info(request,idFesta):
	try:
		festa = Festa.objects.get(pk=idFesta)
	except:
		raise Http404('Festa not found')
	variables = Context({
		'festa': festa,	
        'titlehead': 'Nom de la festa',
		'pagetitle': 'Nom de la festa',
	})
	return render(request,"festa.html",variables)


def index(request): 
	
	variables = Context({
        'titlehead': 'Gestor de Festes',
		'pagetitle': 'Gestor de Festes',
		'contentbody': "Informant de tota la festa d'arreu desde 2013",
		'nomUsuari' : obtenirUsuari(request),
	})
	
	
	return render(request,"index.html",variables)

def obtenirUsuari(request):

	if(request.user.is_authenticated()):
		return request.user.username
	else:
		return "Anonim"

def logout_view(request):
    logout(request)
    # Redirect to a success page.


def ciutats(request): 
	try:
		ciutats = Ciutat.objects.all()
	except Exception:
		raise Http404('Ciutats not found.')
	
	variables = Context({
		'ciutats': ciutats,	
        'titlehead': 'Gestor de Festes',
		'pagetitle': 'Llistat de Ciutats',
	})

	return render(request,"ciutats.html",variables)

def ciutat_info(request,idCiutat):
	try:
		ciutat = Ciutat.objects.get(pk=idCiutat)
	except Exception:
		raise Http404('Ciutat not found.')
	
	variables = Context({
		'ciutat': ciutat,	
        'titlehead': 'Gestor de Festes',
		'pagetitle': ciutat.nom,
	})

	return render(request,"ciutat.html",variables)

def locals_view(request): 
	try:
		locals_obj = Local.objects.all()
	except Exception:
		raise Http404('Ciutats not found.')
	
	variables = Context({
		'locals': locals_obj,	
        'titlehead': 'Gestor de Festes',
		'pagetitle': 'Llistat de Locals',
	})

	return render(request,"locals.html",variables)

def locals_info(request,idLocal): 
	try:
		local = Local.objects.get(pk=idLocal)
		festes = Festa.objects.filter(local=idLocal)
	except Exception:
		raise Http404('Local not found.')
	
	variables = Context({
		'local': local,	
        'titlehead': 'Gestor de Festes',
		'pagetitle': local.nom,
		'festes' : festes,
		'RATING_CHOICES' : LocalReview.RATING_CHOICES,
	})

	return render(request,"local.html",variables)

def locals_ciutat(request,idCiutat): 
	try:
		local = Local.objects.filter(ciutat=idCiutat)
		ciutat = Ciutat.objects.get(pk=idCiutat)
	except Exception:
		raise Http404('Ciutats not found.')
	
	variables = Context({
		'local': local,	
        'titlehead': 'Gestor de Festes',
		'pagetitle': 'Locals de '+ciutat.nom,
		'locals' : local,
	})

	return render(request,"locals.html",variables)


def festes_local(request,idLocal):
	try:
		local = Local.objects.get(pk=idLocal)
		festes = Festa.objects.filter(local=idLocal)
	except Exception:
		raise Http404('Ciutats not found.')
	
	variables = Context({	
        'titlehead': 'Gestor de Festes',
		'pagetitle': local.nom,
		'festes' : festes,
		'local' : idLocal,
	})

	return render(request,"festesLocal.html",variables)


# Forms #

from forms import CiutatForm, LocalForm, FestaForm
from  django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse_lazy

class LoginRequiredMixin(object):

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

class CheckIsOwnerMixin(object):
	def get_object(self, *args, **kwargs):
		obj = super(CheckIsOwnerMixin, self).get_object(*args, **kwargs)
		if not obj.user == self.request.user:
			raise PermissionDenied
		return obj

class CiutatCreate(LoginRequiredMixin , CreateView):
	model = Ciutat
	template_name = 'form.html'
	form_class = CiutatForm
	def form_valid(self,form):
		form.instance.user = self.request.user
		return super(CiutatCreate,self).form_valid(form)

class CiutatUpdate(LoginRequiredMixin, CheckIsOwnerMixin, UpdateView):
	model = Ciutat
	template_name = 'form.html'
	form_class = CiutatForm

class CiutatDelete(LoginRequiredMixin, CheckIsOwnerMixin,DeleteView):
	model = Ciutat
	success_url = reverse_lazy('ciutat_lis')

class LocalCreate(LoginRequiredMixin , CreateView):
	model = Local
	template_name = 'form.html'
	form_class = LocalForm
	def form_valid(self,form):
		form.instance.user = self.request.user
		return super(LocalCreate,self).form_valid(form)

class LocalUpdate(LoginRequiredMixin, CheckIsOwnerMixin, UpdateView):
	model = Local
	template_name = 'form.html'
	form_class = LocalForm

class LocalDelete(LoginRequiredMixin, CheckIsOwnerMixin,DeleteView):
	model = Local
	success_url = reverse_lazy('local_lis')

class FestaCreate(LoginRequiredMixin , CreateView):
	
	model = Festa
	template_name = 'form.html'
	form_class = FestaForm

#	def get_form(self, form_class):
#		return form_class(
#			locals_user=Local.objects.filter(user=self.request.user.id)
#	)

	def form_valid(self,form):
		form.instance.user = self.request.user
		return super(FestaCreate,self).form_valid(form)

class FestaUpdate(LoginRequiredMixin, CheckIsOwnerMixin, UpdateView):
	model = Festa
	template_name = 'form.html'
	form_class = FestaForm

class FestaDelete(LoginRequiredMixin, CheckIsOwnerMixin,DeleteView):
	model = Festa
	success_url = reverse_lazy('festa_lis')

@login_required()
def review(request, pk):
	local = get_object_or_404(Local, pk=pk)
	review = LocalReview(rating=request.POST['rating'],
		comment=request.POST['comment'],
		user=request.user,
		local=local)
	review.save()
	return HttpResponseRedirect(urlresolvers.reverse('local_detail', args=(local.id,)))



# RESTful API #

from rest_framework import generics, permissions
from serializers import LocalSerializer, FestaSerializer, CiutatSerializer

class IsOwnerOrReadOnly(permissions.BasePermission):
	def has_object_permission(self, request, view, obj):
		if request.method in permissions.SAFE_METHODS:
			return True
		return obj.user == request.user

class APILocalList(generics.ListCreateAPIView):
	permission_classes = (IsOwnerOrReadOnly,)
	model = Local
	serializer_class = LocalSerializer

class APILocalDetail(generics.RetrieveUpdateDestroyAPIView):
	permission_classes = (IsOwnerOrReadOnly,)
	model = Local
	serializer_class = LocalSerializer

class APIFestaList(generics.ListCreateAPIView):
	permission_classes = (IsOwnerOrReadOnly,)
	model = Festa
	serializer_class = FestaSerializer

class APIFestaDetail(generics.RetrieveUpdateDestroyAPIView):
	permission_classes = (IsOwnerOrReadOnly,)
	model = Festa
	serializer_class = FestaSerializer

class APICiutatList(generics.ListCreateAPIView):
	permission_classes = (IsOwnerOrReadOnly,)
	model = Ciutat
	serializer_class = CiutatSerializer

class APICiutatDetail(generics.RetrieveUpdateDestroyAPIView):
	permission_classes = (IsOwnerOrReadOnly,)
	model = Ciutat
	serializer_class = CiutatSerializer

web/gestorFestes/templates/base.html
{%load staticfiles%}
<!DOCTYPE html> 
<html>
<head>
	<title>Gestor de Festes</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script> 
</head>
<body>
	<div class="structBody">
		<nav>
			<ul class="fancyNav">
				<li><a href="/"><span>Index</span></a></li>
				<li><a href="/festes"><span>Festes</span></a></li>
				<li><a href="/ciutats"><span>Ciutats</span></a></li>
				<li><a href="/locals"><span>Locals</span></a></li>
				{% if user.username %}
				<li><a href="/admin"><span>Admin</span></a></li>
				{% else %}
				<li><a href="/login"><span>Admin</span></a></li>
				{% endif %}
			</ul>
			<div class="userButton">
				{% if user.username %}
				<a rel="external" href="/logout" id="button" class="on">&#xF011;</a>
				<span></span>
				<div>Logout</div>
				{% else %}
				<a rel="external" href="/login" id="button">&#xF011;</a>
				<span></span>
				<div>Login</div>
				{% endif %}
			</div>
		</nav>
		<section>
			{% block content %}{% endblock %}
		</section>
	</div>
</body>
</html>

web/gestorFestes/templates/ciutat.html
{% extends "base.html" %}
{% block content %}
<div class="backButton" onclick="history.go(-1)" /><i class="icon-arrow-left"></i>Back</div>
<span vocab="http://schema.org/" typeof="PostalAddress">
	<div class="pagetitle">
		<h1 property="name">{{ pagetitle }}</h1>
		<p>{{ contentbody }}</p>
	</div>
	
	{% if ciutat %}
		{% if user.username and ciutat.user == user  %}
			<a href="/ciutats/{{ciutat.id}}/edit">modificar ciutat</a>
			<a href="/ciutats/{{ciutat.id}}/delete">eliminar ciutat</a>
		{% endif %}
	
		<ul>
			<li>	
				<p>Provincia: <span property="addressRegion">{{ ciutat.provincia }}</span></p>
				<p>Codi Postal: <span property="postalCode">{{ ciutat.cp }}</span></p>
			</li>
		</ul>
		<form><input type="button" value=" Tornar Enrrera " onclick="history.go(-1)" /></form>
</span>
	{% else %}
		<p>No Ciutat</p>
	{% endif %}
{% endblock %}

web/gestorFestes/templates/ciutats.html
{% extends "base.html" %}
{% block content %}
<div class="backButton" onclick="history.go(-1)" /><i class="icon-arrow-left"></i>Back</div>
	<div class="pagetitle">
		<h1>{{ pagetitle }}</h1>
		<p>{{ contentbody }}</p>
	</div>
		{% if user.username %}<a href="/ciutats/create">afegir ciutat</a>{% endif %}
		{% if ciutats %}	
		<ul class="messy">
		{% for ciutat in ciutats %}
		<li>
			<p><h3><a href="/ciutats/{{ciutat.id}}"> {{ciutat.nom}}</a></h3></p>
		</li>
		{% endfor %}
		</ul>
		{% else %}
		{% endif %}
{% endblock %}

web/gestorFestes/templates/festa.html
{% extends "base.html" %}
{% block content %}
<div class="backButton" onclick="history.go(-1)" /><i class="icon-arrow-left"></i>Back</div>
<span vocab="http://schema.org/" typeof="MusicEvent">
	<div class="pagetitle">
		<h1 property="name" >{{festa.titol}}</h1>
		<p>{{ contentbody }}</p>
	</div>

	{% if festa %}
		{% if user.username and festa.user == user  %}
			<a href="/festes/{{festa.id}}/edit">modificar festa</a>
			<a href="/festes/{{festa.id}}/delete">Eliminar festes</a>
		{% endif %}
		<ul>
			<li>
			<p>Descripcio: <span property="description">{{ festa.descripcio}}</span></p> 
			<span typeof="EntertainmentBussines">
				<p>Local: <span property="name">{{ festa.local.nom}}</p>
			</span>
			<p>Data: <span property="startDate">{{ festa.data }}</span></p>
			<span property="image" content="media/{{ festa.imatge }}"><img src="../../media/{{ festa.imatge }}"></span>
			</li>
		</ul>
</span>
	{% else %}
	<p>No Party</p>
	{% endif %}

	
{% endblock %}

web/gestorFestes/templates/festes.html
{% extends "base.html" %}
{% block content %}
<div class="backButton" onclick="history.go(-1)" /><i class="icon-arrow-left"></i>Back</div>
	<div class="pagetitle">
		<h1>{{ pagetitle }}</h1>
		<p>{{ contentbody }}</p>
	</div>
	{% if user.username %}<a href="/festes/create">afegir festa</a>{% endif %}
	{% if festes %}
	<ul class="messy">
		{% for festa in festes %}
		<li>
		<p><a href="/festes/{{festa.id}}"<h3>{{festa.titol}}</h3></a></p>
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<p>No Party</p>
	{% endif %}
{% endblock %}

web/gestorFestes/templates/festesLocal.html
{% extends "base.html" %}
{% block content %}
<div class="backButton" onclick="history.go(-1)" /><i class="icon-arrow-left"></i>Back</div>
	<div class="pagetitle">
		<h1>{{ pagetitle }}</h1>
		<p>{{ contentbody }}</p>
	</div>
	{% if festes %}
	<ul class="messy">

		{% for festa in festes %}
		<li>
		<p><a href="/festesLocal/festa/{{festa.id}}"<h3>{{festa.titol}}</h3></a></p>

		</li>
		{% endfor %}
	</ul>
	
	{% else %}
	<p>No Party</p>
	{% endif %}
{% endblock %}

web/gestorFestes/templates/form.html
{% extends "base.html" %}
{%load staticfiles%}
{% block content %}
<script type="text/javascript">
	$(function() {
		$( "#id_data" ).datepicker();
		$.getJSON("{% static "provincies.json" %}", function(provincies){
			$("#id_provincia").autocomplete({source: provincies});
		});
		getProvince = function(){
			value = $("#id_provincia").val();
			if(value == "Lleida"){return "25"}
			if(value == "Barcelona"){return "08"}
			if(value == "Girona"){return "17"}
			if(value == "Tarragona"){return "43"}
			if(value == ""){return ""}
		};

		$("#id_nom").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            lang: "es",
                            continentCode: "EU",
                            country: "ES",
                            adminCode1: "56",
                            adminCode2_startsWith: getProvince(),
                            name_startsWith: request.term
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    postalCode: item.postalCode,
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_cp").val(ui.item.postalCode);
                    }
                }
            });
	});


</script>
<div class="backButton" onclick="history.go(-1)" /><i class="icon-arrow-left"></i>Back</div>
	<div class="pagetitle">
		<p>Afegir</p>
	</div>
		<form method="post" action="" enctype="multipart/form-data">
		 {% csrf_token %}
		 <table>
		 	{{ form.as_table}}
		 </table>
		 <input type="submit" value="Submit">
		</form>


{% endblock %}

web/gestorFestes/templates/index.html
{% extends "base.html" %}
{% block content %}
	<div class="pagetitle">
		<h1>{{ pagetitle }}</h1>
		<p>{{ contentbody }}</p>
	</div>
	<div class="indexLogo">
		<div class="handLeft"></div>
		<div class="handRight"></div>
	</div>
{% endblock %}

web/gestorFestes/templates/locals.html
{% extends "base.html" %}
{% block content %}
<div class="backButton" onclick="history.go(-1)" /><i class="icon-arrow-left"></i>Back</div>
	<div class="pagetitle">
		<h1>{{ pagetitle }}</h1>
		<p>{{ contentbody }}</p>
	</div>
	{% if user.username %}<a href="/locals/create">afegir local</a>{% endif %}
	{% if locals %}
	<ul class="messy">
		{% for local in locals %}
		<li>
		<p><a href="/locals/{{local.id}}"<h3>{{local.nom}}</h3></a></p>
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<p>No Party</p>
	{% endif %}
{% endblock %}

web/gestorFestes/templates/login.html
<FORM method=post action="control">
<TABLE BORDER=0>
<TR>
	<TD>Nom usuari</TD>
	<TD>
	<INPUT type=text name="username">
	</TD>
</TR>

<TR>
	<TD>Password</TD>
	<TD>
	<INPUT type=text name="password">
	</TD>
</TR>
<TR>
	<TD COLSPAN=2>
	<INPUT type="submit" value="Enviar">
	</TD>
</TR>
</TABLE>
</FORM>

web/gestorFestes/templates/userpage.html
<!DOCTYPE html> 
<html>
<head>
<title>{{ username }} Party's</title>
</head>
<body>
<h1>Festes organitzades per: {{ username }}</h1>
{% if festes %}
<ul>
{% for festa in festes %}
<li>
	<p><h3>{{festa.titol}}</h3></p>
	<p>{{ festa.descripcio}}</p> 
	<p>Data: {{ festa.data }}</p>
	<img src="../../media/{{ festa.imatge }}">
</li>
{% endfor %}
</ul>
{% else %}
<p>No Party</p>
{% endif %}
<p><a href="../../">INICI</a></p>
</body>
</html>